version: '3.8'

services:
  web:
    image: uas-web-website:latest
    build: .
    container_name: cat-adoption
    ports:
      - "8090:80" # <-- JATAH PORT WEB UTAMA MEREKA! (Nembak port 80 internal container)
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: monitoring_cat_adoption
    ports:
      - "3012:3001" # <-- JATAH PORT MONITORING UPTIME KUMA MEREKA!
    volumes:
      - uptime-kuma-cat-data:/app/data
    restart: always

volumes:
  uptime-kuma-cat-data: